### ISSUE TITLE
please expand README with usage example

### ISSUE THREAD

**Issue by mariusa** [geospoc/v-mapbox-geocoder#58]
Hi,

You mention about using these options
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md

but it's not obvious from the README how to do that. THey say

```
var geocoder = new MapboxGeocoder({ accessToken: mapboxgl.accessToken });
map.addControl(geocoder);
```
but there's no ```map``` to add to.

Would you please add an example on how to set proximity, set & query the input?

Thanks!

**Comment by vinayakkulkarni** [comment]
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters

All those above parameters are actually props that are sent to the [`MglGeocoderControl`](https://github.com/geospoc/v-mapbox-geocoder#usage) template, you don't have to instantiate geocoder by using `addControl` as the component is a wrapper around that only.

a simple example would be:
```html
<MglGeocoderControl :track-proximity="true" :clear-on-blur="true" language="en-US" />
```

**Comment by mariusa** [comment]
Thanks!
